// Centralized disclaimer copy so it reads identically everywhere it appears.

export const DISCLAIMER_SHORT =
  'Just for fun · AI-generated · not a real psychological test'

export const DISCLAIMER_PARAGRAPHS: string[] = [
  'Quirk is a playful, for-entertainment personality quiz. All questions, type names, and descriptions were generated by Claude (an AI assistant) specifically for this app.',
  'Quirk is NOT the Myers-Briggs Type Indicator® instrument and is not affiliated with, endorsed by, or connected to The Myers & Briggs Foundation or any official personality assessment. "Myers-Briggs" and "MBTI" are registered trademarks of their respective owners; the four-letter format is used here only as a familiar, generic framing.',
  'This quiz has no scientific validity and should not be used for clinical, diagnostic, hiring, educational, or any other consequential decisions. Results are a lighthearted reflection, not a fact about who you are.',
  'No answers leave your device. Your responses and history are stored locally in your browser and never sent to a server.',
]
